# Generated by Django 6.0.1 on 2026-01-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco', models.FloatField(verbose_name='Preco')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('promocao', models.BooleanField(verbose_name='Promocao')),
            ],
        ),
    ]
