# Generated by Django 6.0.1 on 2026-01-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePessoa', models.CharField(max_length=150, verbose_name='Pessoa')),
                ('nomeTec', models.CharField(max_length=50, verbose_name='Tecnologia')),
                ('tempo', models.IntegerField(verbose_name='Tempo')),
            ],
        ),
    ]
