# Generated by Django 6.0.1 on 2026-01-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tecnologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaEstudo', models.CharField(max_length=100, verbose_name='EstudoDia')),
                ('materiaEstudo', models.CharField(max_length=100, verbose_name='EstudoMateria')),
            ],
        ),
    ]
